// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	null "github.com/volatiletech/null/v8"
)

type CreateAccessLog struct {
	Path               string       `json:"path"`
	RequestBody        *null.String `json:"request_body"`
	RequestHeaders     interface{}  `json:"request_headers"`
	ResponseBody       interface{}  `json:"response_body"`
	ResponseHeaders    interface{}  `json:"response_headers"`
	ResponseCode       int          `json:"response_code"`
	ProcessingDuration int          `json:"processing_duration"`
	RequestMethod      string       `json:"request_method"`
	UserID             *null.String `json:"user_id"`
	IPAddress          string       `json:"ip_address"`
}

type CreateImage struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Size   int    `json:"size"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

type CreateJob struct {
	Type        *null.String `json:"type"`
	Priority    *int         `json:"priority"`
	Source      *null.String `json:"source"`
	Data        interface{}  `json:"data"`
	RunAt       *time.Time   `json:"run_at"`
	FailureData interface{}  `json:"failure_data"`
	MaxRetries  *int         `json:"max_retries"`
	RetryCount  *int         `json:"retry_count"`
	Status      *string      `json:"status"`
	FinishedAt  *time.Time   `json:"finished_at"`
}

type CreateTokenIssuance struct {
	UserID    string `json:"user_id"`
	IPAddress string `json:"ip_address"`
}

type CreateUser struct {
	Name              string       `json:"name"`
	Login             *null.String `json:"login"`
	Email             string       `json:"email"`
	Sub               *null.String `json:"sub"`
	Roles             []string     `json:"roles"`
	Image             *null.String `json:"image"`
	Birthday          *time.Time   `json:"birthday"`
	GenderSelfDefined *null.Bool   `json:"gender_self_defined"`
	Gender            *null.String `json:"gender"`
	Location          *null.String `json:"location"`
	Phone             *null.String `json:"phone"`
}

type UpdateAccessLog struct {
	Path               *string      `json:"path"`
	RequestBody        *null.String `json:"request_body"`
	ResponseCode       *int         `json:"response_code"`
	ProcessingDuration *int         `json:"processing_duration"`
	RequestMethod      *string      `json:"request_method"`
	UserID             *null.String `json:"user_id"`
	IPAddress          *string      `json:"ip_address"`
}

type UpdateImage struct {
	Name   *string `json:"name"`
	Type   *string `json:"type"`
	Size   *int    `json:"size"`
	Width  *int    `json:"width"`
	Height *int    `json:"height"`
}

type UpdateJob struct {
	Type       *null.String `json:"type"`
	Priority   *int         `json:"priority"`
	Source     *null.String `json:"source"`
	RunAt      *time.Time   `json:"run_at"`
	MaxRetries *int         `json:"max_retries"`
	RetryCount *int         `json:"retry_count"`
	Status     *string      `json:"status"`
	FinishedAt *time.Time   `json:"finished_at"`
}

type UpdateTokenIssuance struct {
	UserID    *string `json:"user_id"`
	IPAddress *string `json:"ip_address"`
}

type UpdateUser struct {
	Name              *string      `json:"name"`
	Login             *null.String `json:"login"`
	Email             *string      `json:"email"`
	Sub               *null.String `json:"sub"`
	Roles             []*string    `json:"roles"`
	Image             *null.String `json:"image"`
	Birthday          *time.Time   `json:"birthday"`
	GenderSelfDefined *null.Bool   `json:"gender_self_defined"`
	Gender            *null.String `json:"gender"`
	Location          *null.String `json:"location"`
	Phone             *null.String `json:"phone"`
}
