// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package modelcrud

import (
	"github.com/calebhiebert/go-vue-template/api"
	"github.com/gin-gonic/gin"
)

func (gcc *GeneratedCrudController) RegisterUsers(rg *gin.RouterGroup) {
	rg.GET("/users/:id", gcc.GetUserByID)
	rg.GET("/users", gcc.GetUsers)
	rg.PUT("/users/:id", gcc.UpdateUserByID)
	rg.POST("/users", gcc.CreateUser)
	rg.DELETE("/users/:id", gcc.DeleteUserByID)
	rg.DELETE("/users", gcc.BulkDeleteUsersByIDs)
	rg.POST("/users/:id/unDelete", gcc.UnDeleteUserByID)
}

var UsersAdmin = api.AdminModel{
	Name:          "Users",
	NameSingular:  "User",
	CanSoftDelete: true,
	URLName:       "users",
	DataName:      "users",
	Fields: []*api.AdminModelField{
		&api.AdminModelField{
			ID:       "id",
			Name:     "ID",
			Nullable: false,
			Required: true,
			FilterOperations: []string{
				"eq", "null"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      false,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "uuid",
		},
		&api.AdminModelField{
			ID:       "name",
			Name:     "Name",
			Nullable: false,
			Required: true,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "login",
			Name:     "Login",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "email",
			Name:     "Email",
			Nullable: false,
			Required: true,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     true,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "sub",
			Name:     "Sub",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "roles",
			Name:     "Roles",
			Nullable: false,
			Required: false,
			FilterOperations: []string{
				"eq", "null"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "array",
		},
		&api.AdminModelField{
			ID:       "image",
			Name:     "Image",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "birthday",
			Name:     "Birthday",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "gt", "lt", "gte", "lte"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "time",
		},
		&api.AdminModelField{
			ID:       "gender_self_defined",
			Name:     "GenderSelfDefined",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "bool",
		},
		&api.AdminModelField{
			ID:       "gender",
			Name:     "Gender",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "location",
			Name:     "Location",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "phone",
			Name:     "Phone",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "cont"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      true,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "string",
		},
		&api.AdminModelField{
			ID:       "created_at",
			Name:     "CreatedAt",
			Nullable: false,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "gt", "lt", "gte", "lte"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      false,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "time",
		},
		&api.AdminModelField{
			ID:       "updated_at",
			Name:     "UpdatedAt",
			Nullable: false,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "gt", "lt", "gte", "lte"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      false,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: true,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "time",
		},
		&api.AdminModelField{
			ID:       "deleted_at",
			Name:     "DeletedAt",
			Nullable: true,
			Required: false,
			FilterOperations: []string{
				"eq", "null", "gt", "lt", "gte", "lte"},
			ForeignFields: []api.AdminModelForeignField{},
			Editable:      false,
			Config: api.AdminModelFieldConfig{
				ShowOnGraph: false,
				Editable:    true,
				IsEmail:     false,
			},
			Type: "time",
		},
	},
}

type UsersModelConfigType struct {
	ID api.AdminModelFieldConfig

	Name api.AdminModelFieldConfig

	Login api.AdminModelFieldConfig

	Email api.AdminModelFieldConfig

	Sub api.AdminModelFieldConfig

	Roles api.AdminModelFieldConfig

	Image api.AdminModelFieldConfig

	Birthday api.AdminModelFieldConfig

	GenderSelfDefined api.AdminModelFieldConfig

	Gender api.AdminModelFieldConfig

	Location api.AdminModelFieldConfig

	Phone api.AdminModelFieldConfig

	CreatedAt api.AdminModelFieldConfig

	UpdatedAt api.AdminModelFieldConfig

	DeletedAt api.AdminModelFieldConfig
}

var UsersModelConfig = UsersModelConfigType{

	ID: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Name: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Login: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Email: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Sub: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Roles: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Image: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Birthday: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	GenderSelfDefined: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Gender: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Location: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	Phone: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	CreatedAt: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	UpdatedAt: api.AdminModelFieldConfig{
		ShowOnGraph: true,
		Editable:    true,
		IsEmail:     false,
	},
	DeletedAt: api.AdminModelFieldConfig{
		ShowOnGraph: false,
		Editable:    true,
		IsEmail:     false,
	},
}

func (c UsersModelConfigType) Apply() {

	UsersAdmin.Fields[0].Config = c.ID

	UsersAdmin.Fields[1].Config = c.Name

	UsersAdmin.Fields[2].Config = c.Login

	UsersAdmin.Fields[3].Config = c.Email

	UsersAdmin.Fields[5].Config = c.Sub

	UsersAdmin.Fields[6].Config = c.Roles

	UsersAdmin.Fields[7].Config = c.Image

	UsersAdmin.Fields[8].Config = c.Birthday

	UsersAdmin.Fields[9].Config = c.GenderSelfDefined

	UsersAdmin.Fields[10].Config = c.Gender

	UsersAdmin.Fields[11].Config = c.Location

	UsersAdmin.Fields[12].Config = c.Phone

	UsersAdmin.Fields[13].Config = c.CreatedAt

	UsersAdmin.Fields[14].Config = c.UpdatedAt

	UsersAdmin.Fields[15].Config = c.DeletedAt

}
