// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AccessLogs", testAccessLogs)
	t.Run("Images", testImages)
	t.Run("Jobs", testJobs)
	t.Run("TokenIssuances", testTokenIssuances)
	t.Run("Users", testUsers)
}

func TestSoftDelete(t *testing.T) {
	t.Run("Images", testImagesSoftDelete)
	t.Run("Users", testUsersSoftDelete)
}

func TestQuerySoftDeleteAll(t *testing.T) {
	t.Run("Images", testImagesQuerySoftDeleteAll)
	t.Run("Users", testUsersQuerySoftDeleteAll)
}

func TestSliceSoftDeleteAll(t *testing.T) {
	t.Run("Images", testImagesSliceSoftDeleteAll)
	t.Run("Users", testUsersSliceSoftDeleteAll)
}

func TestDelete(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsDelete)
	t.Run("Images", testImagesDelete)
	t.Run("Jobs", testJobsDelete)
	t.Run("TokenIssuances", testTokenIssuancesDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsQueryDeleteAll)
	t.Run("Images", testImagesQueryDeleteAll)
	t.Run("Jobs", testJobsQueryDeleteAll)
	t.Run("TokenIssuances", testTokenIssuancesQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsSliceDeleteAll)
	t.Run("Images", testImagesSliceDeleteAll)
	t.Run("Jobs", testJobsSliceDeleteAll)
	t.Run("TokenIssuances", testTokenIssuancesSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsExists)
	t.Run("Images", testImagesExists)
	t.Run("Jobs", testJobsExists)
	t.Run("TokenIssuances", testTokenIssuancesExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsFind)
	t.Run("Images", testImagesFind)
	t.Run("Jobs", testJobsFind)
	t.Run("TokenIssuances", testTokenIssuancesFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsBind)
	t.Run("Images", testImagesBind)
	t.Run("Jobs", testJobsBind)
	t.Run("TokenIssuances", testTokenIssuancesBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsOne)
	t.Run("Images", testImagesOne)
	t.Run("Jobs", testJobsOne)
	t.Run("TokenIssuances", testTokenIssuancesOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsAll)
	t.Run("Images", testImagesAll)
	t.Run("Jobs", testJobsAll)
	t.Run("TokenIssuances", testTokenIssuancesAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsCount)
	t.Run("Images", testImagesCount)
	t.Run("Jobs", testJobsCount)
	t.Run("TokenIssuances", testTokenIssuancesCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsHooks)
	t.Run("Images", testImagesHooks)
	t.Run("Jobs", testJobsHooks)
	t.Run("TokenIssuances", testTokenIssuancesHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsInsert)
	t.Run("AccessLogs", testAccessLogsInsertWhitelist)
	t.Run("Images", testImagesInsert)
	t.Run("Images", testImagesInsertWhitelist)
	t.Run("Jobs", testJobsInsert)
	t.Run("Jobs", testJobsInsertWhitelist)
	t.Run("TokenIssuances", testTokenIssuancesInsert)
	t.Run("TokenIssuances", testTokenIssuancesInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("AccessLogToUserUsingUser", testAccessLogToOneUserUsingUser)
	t.Run("TokenIssuanceToUserUsingUser", testTokenIssuanceToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("UserToAccessLogs", testUserToManyAccessLogs)
	t.Run("UserToTokenIssuances", testUserToManyTokenIssuances)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("AccessLogToUserUsingAccessLogs", testAccessLogToOneSetOpUserUsingUser)
	t.Run("TokenIssuanceToUserUsingTokenIssuances", testTokenIssuanceToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("AccessLogToUserUsingAccessLogs", testAccessLogToOneRemoveOpUserUsingUser)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("UserToAccessLogs", testUserToManyAddOpAccessLogs)
	t.Run("UserToTokenIssuances", testUserToManyAddOpTokenIssuances)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("UserToAccessLogs", testUserToManySetOpAccessLogs)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("UserToAccessLogs", testUserToManyRemoveOpAccessLogs)
}

func TestReload(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsReload)
	t.Run("Images", testImagesReload)
	t.Run("Jobs", testJobsReload)
	t.Run("TokenIssuances", testTokenIssuancesReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsReloadAll)
	t.Run("Images", testImagesReloadAll)
	t.Run("Jobs", testJobsReloadAll)
	t.Run("TokenIssuances", testTokenIssuancesReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsSelect)
	t.Run("Images", testImagesSelect)
	t.Run("Jobs", testJobsSelect)
	t.Run("TokenIssuances", testTokenIssuancesSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsUpdate)
	t.Run("Images", testImagesUpdate)
	t.Run("Jobs", testJobsUpdate)
	t.Run("TokenIssuances", testTokenIssuancesUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AccessLogs", testAccessLogsSliceUpdateAll)
	t.Run("Images", testImagesSliceUpdateAll)
	t.Run("Jobs", testJobsSliceUpdateAll)
	t.Run("TokenIssuances", testTokenIssuancesSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
