// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	TestRelation string
	TestTable    string
	Users        string
}{
	TestRelation: "test_relation",
	TestTable:    "test_table",
	Users:        "users",
}
